name: Build Firmware

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc-avr avr-libc wget tar
      - name: Install arm-none-eabi-gcc 7.3.1
        run: |
          GCC_VERSION="7-2018q2"
          GCC_DIR="gcc-arm-none-eabi-7-2018-q2-update"
          GCC_TAR="${GCC_DIR}-linux.tar.bz2"
          wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/${GCC_VERSION}/${GCC_TAR}
          tar -xjf ${GCC_TAR}
          echo "$PWD/${GCC_DIR}/bin" >> $GITHUB_PATH
          # export PATH="$PWD/${GCC_DIR}/bin:$PATH" // sous linux

      - name: Verify compiler version
        run: arm-none-eabi-gcc --version

      - name: Build project
        run: |
          cd firmware
          make all

      - name: Update firmware binary file
        run: |
          mkdir -p firmware/release
          echo -n "AV04" | dd of=firmware/build_stm6/inlretro_stm.bin bs=1 seek=$((0x800)) conv=notrunc
          cp firmware/build_stm6/inlretro_stm.bin firmware/release/inlretro_stm6_AV04.bin
          echo -n "AV04" | dd of=firmware/build_stmn/inlretro_stm.bin bs=1 seek=$((0x800)) conv=notrunc
          cp firmware/build_stmn/inlretro_stm.bin firmware/release/inlretro_stmn_AV04.bin
          cp firmware/build_avr/* firmware/release/

      - name: Upload INLretro firmware
        uses: actions/upload-artifact@v5
        with:
          name: INLretro-firmware-AV04
          path: firmware/release
