name: release

on:
  push:
    tags: ["v*.*.*"]

permissions:
  actions: read
  contents: write

jobs:
  build:
    name: Build release artifacts
    uses: ./.github/workflows/build.yml

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-22.04

    steps:
      - name: Download build artifacts from this workflow
        uses: dawidd6/action-download-artifact@v3
        with:
          run_id: ${{ github.run_id }}
          skip_unpack: true
          path: release

      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          files: release/**
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
